TechTreeWebApp/Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Identity;
using TechTreeWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using TechTreeWebApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;
using LoginModel = TechTreeWebApp.Models.LoginModel;
using RegistrationModel = TechTreeWebApp.Models.RegistrationModel;
using Microsoft.EntityFrameworkCore;
using TechTreeWebApp.Entities;

namespace TechTreeWebApp.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public UserAuthController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ApplicationDbContext context) 
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
        }
        [HttpPost]
        [AllowAnonymous] //no security restrictions are imposed
        [ValidateAntiForgeryToken] //denotes an action filter, request made to this filter are blocked unless the request a valid anti forgery token -- preventing cross site forgery
        public async Task<IActionResult> Login(LoginModel loginModel) 
        {
            loginModel.LoginInValid = "true";
            ApplicationUser signedUser = await _userManager.FindByEmailAsync(loginModel.Email); // UserName and Email get Interchanged
            if (ModelState.IsValid) 
            {
                var identityresult = await _signInManager.PasswordSignInAsync(signedUser.UserName, loginModel.Password, loginModel.RememberMe, lockoutOnFailure: true);
                                                                        
                if (identityresult.Succeeded)
                {
                    loginModel.LoginInValid = "";
                } 
                else
                {
                    ModelState.AddModelError(string.Empty, "Error, invalid login attempt");                    
                }
            }
            return PartialView("_UserLoginPartial", loginModel);
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string? returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            if(returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(RegistrationModel registerModel)
        {
            registerModel.RegistrationInValid = "true";
            // ModelState represents a collection of name and value pairs that was submitted to Post
            if (ModelState.IsValid) //is a property of controller object, can be accessed by UserAuth because it inherits it.
            {
                ApplicationUser applicationUser = new ApplicationUser()
                {
                    UserName = registerModel.UserName,
                    Email = registerModel.Email,
                    FirstName = registerModel.FirstName,
                    LastName = registerModel.LastName,
                    Address1 = registerModel.Address1,
                    Address2 = registerModel.Address2,
                    PostCode = registerModel.PostCode,
                    PhoneNumber = registerModel.PhoneNumber.ToString(),
                };
                //if(await UserNameExists(applicationUser.UserName))
                //{
                //    ModelState.AddModelError(string.Empty, "Error, Username already exists");
                //    return PartialView("_UserRegistrationPartial", registerModel);
                //}
                var identityresult = await _userManager.CreateAsync(applicationUser, registerModel.Password);                
                if (identityresult.Succeeded)
                {                    
                    registerModel.RegistrationInValid = "";
                    await _signInManager.SignInAsync(applicationUser, isPersistent: false);
                    if (registerModel.CategoryId != 0) // So public user choosed a course category
                    {
                        await AddCategoryToUser(applicationUser.Id, registerModel.CategoryId);
                    }
                    return PartialView("_UserRegistrationPartial", registerModel); //returning Client-side html code to _UserREgistrationPartial
                }
                AddErrortoModelState(identityresult);
            }            
            return PartialView("_UserRegistrationPartial", registerModel);
        }
        [AllowAnonymous]       
        public async Task<bool> UserNameExists(string userName)
        {
            var result = await _context.Users.AnyAsync(user => user.UserName.ToUpper() == userName.ToUpper());
            return (result) ? true : false;
        }
        private void AddErrortoModelState(IdentityResult identityResult) //	We should loop through the errors collec, made available on the Identity state, then send the relevant exception messages to the ModelState
        {
            foreach (var error in identityResult.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }
        private async Task AddCategoryToUser(string userId, int categoryId) //cannot await void!
        {
            UserCategory userCategory = new UserCategory()
            {
                UserId = userId,
                CategoryId = categoryId
            };
            _context.UserCategory.Add(userCategory);
            await _context.SaveChangesAsync();
        }
    }
}

TechTreeWebApp/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore;
@using TechTreeWebApp.Data;
<!-- 	Admin Menu should be restricted from non-administrators-->
@inject SignInManager<ApplicationUser> SigninManager;
@inject UserManager<ApplicationUser> UserManager;
<!-- Dependency Injection to inject generic type SignINManager and .. Into this view -- integrating identity technolog-->
<!-- If user is logged in and is part of the Admin Role-->
@if(SigninManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
<!-- This is a razor view-->
<!-- A Bootstrap refers to a smaller system that boots up a much larger system.-->
<div class="nav-item dropdown show">        
    <a class="dropdown-toggle nav-link text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-table-list"></i>
    Admin
    </a>
    <ul class="dropdown-menu">
        <!-- Naming Convention: Remove suffix in Controller i.e "CategoryController"-->
        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">
            Categories
         </a></li>
            <!-- UsersToCategory.js linking menu item to UserCategory.Index.cshtml-->
            <li><a class="dropdown-item" asp-area="Admin" asp-controller="UserCategory" asp-action="Index">Users to Categories</a></li>
        <li><a class="dropdown-divider"></a></li>
        <li><a class="dropdown-item" asp-area="Admin" asp-controller="MediaType" asp-action="Index">Media</a></li>
    </ul>
</div>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" href="#CoursesSection"><i class="fa-solid fa-box-open"></i> Courses Offered</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#ContactUsSection"><i class="fa-solid fa-envelope"></i> Contact Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#AboutUsSection"><i class="fa-solid fa-circle-info"></i> About Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
}

TechTreeWebApp/Views/Shared/_AutoScriptsPartial.cshtml
<!-- This is a using statement for .js-->
<!-- Including unobtrusive client-side validation to ensure more responsiveness of modal-login -->
<!-- Contains 2 refs to jQuery files, which contain form-field validation for the client -->

<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/UserRegister.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlert.js" asp-append-version="true"></script>
<script src="~/js/UserOnBlurryEvent.js" asp-append-version="true"></script>

TechTreeWebApp/Views/Shared/_DateScriptPartial.cshtml
<script src="~/js/datefunction.js"></script>
<script src="~/js/datepicker.js"></script>

TechTreeWebApp/Views/Shared/_DefaultHomePageContentPartial.cshtml
@* All includes are located in _ViewImports.cshtml *@
@model IEnumerable<Category>

<!-- Hero Section -->
<div class="hero section"> 
    <!-- Refer to site.css for the design referencing -->
    <!-- img-fluid means providing screen size responsizeness -->
    <img class="img-fluid" src="~/Images/HeroImage.png"/>
    <div class="hero-heading"> <!-- contains the heading text -->
        <h2 class="hero-heading-text"> Learn software development at <strong>TechTree</strong></h2>        
        <a id="HeroRegister_btn" class="btn btn-outline-info btn-lg text-light hero-register-button" data-bs-toggle="modal" data-bs-target="#UserRegistrationModal"> Register</a>
    </div>
</div>
<!-- Courses Section -->
<hr class="section-divider"/>
<!-- N: Layout.cshtml href="#CoursesSection" etc when pressed will navigate user down to here-->
<div id="CoursesSection" class="courses section">
    <h3 class="section-header">Courses</h3>
    @{
        const int itemsperRow = 4;
        var count = Model.Count() / itemsperRow; // We want 4 parts displayed per row
        var categoryList = new List<Category>();
    }
    <!-- Extract the Category Data for each row; Linq's' Skip(index) we start from a certain position, then take 4 Data-->
    @for(int i = 0; i <= count; i++)
    {
        categoryList = Model.Skip(i * itemsperRow).Take(itemsperRow).ToList();
                <partial name="_DisplayCardRowPartial" model="categoryList"/>    
    }
</div>
<!-- Contact Us Section -->
<hr class="section-divider" />
<div id="ContactUsSection" class="contact-us section">
    <h3 class="col-md-5 section-header"> Contact Us</h3>
    <div class="col-md-5"> 
        Email us for your inqueries. We'd be happy to discuss with you.
    </div>
    <div id="mailResult"></div>
    <div class="mt-3">
        <div class="col-md-8">
            <form action="#" method="post" id="mailform">
                <input type="hidden" />
                <div class="form-group">
                    <label for="name" class="control-label">Name: </label>
                    <input type="text" class="form-control" name="name" id="name" required="">

                </div>
                <div class="form-group">
                    <label for="email" class="control-label">Email: </label>
                    <input type="email" class="form-control" name="recipientEmail" id="email" required="">

                </div>
                <div class="form-group">
                    <label for="messageBody" class="control-label">Message: </label>
                    <textarea class="form-control" name="body" cols="30" rows="8" id="messagebody"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="submit" value="Send" class="btn btn-outline-info ml-auto" />
                </div>  
            </form>
        </div>
    </div>
</div>
<!-- About Us Section -->
<hr class="section-divider" />
<div id="AboutUsSection" class="about-us section">
    <div class="col-md-5 section-header">About Us</div> 
    <div class="mt-3 mb-5">
        <div class="col-md-5">
            <p>
                Developed by Eric Jay Catayas, <strong>TechTree</strong> offers a comprehensive online learning platform for users. The administrator area provides seamless uploading and management of online courses and materials.
            </p>
        </div>
    </div>
</div>

TechTreeWebApp/Views/Shared/_DisplayCardRowPartial.cshtml
@* We're separating the code that extracts the data and code that displays the data*@
@model IEnumerable<Category> 
@if (Model.Count() > 0)
{

    <div class="row mt-3">
        @foreach (var category in Model)
        {
            <div class="col-md-3">
                 <a href="#" class="RegisterLink text-dark" data-categoryId="@category.Id" style="text-decoration: none;"> @* data-categoryId is an attribute we can use to store and get the categoryId *@
                    <div class="card">
                        <img class="img-thumbnail" src="@category.ThumbnailImagePath" alt="@category.Title" />
                        <div class="card-body">
                            <h5 class="card-title">@category.Title</h5>
                            @if (category.Description.Length > 130)
                            {
                                <p class="card-text">@category.Description.Substring(0,130)...</p>
                            }
                            else
                            {                                
                                <p class="card-text">@category.Description</p>
                            }
                        </div>
                    </div>
                 </a>
            </div>
        }
    </div>
}

TechTreeWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechTreeWebApp</title>
    <link rel="icon" href="~/Images/techtree-32x32.png" sizes="32x32" type="image/png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechTreeWebApp.styles.css" asp-append-version="true" />
    <link href="~/fontawesome-free-6.2.1-web/css/all.min.css" rel="stylesheet" /> <!-- Another third-part folder! -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top"> <!-- Fixed-top means the heading won't scroll down with the user -->
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/Untransparent.png" height="35"/> TechTree</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i> Home</a>
                        </li>                        
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" /> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 main-default"> <!-- Defining space between main section and the heading menu within the layout view R: site.css -->
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TechTreeWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TechTreeWebApp/Views/Shared/_UserLoginPartial.cshtml
@model TechTreeWebApp.Models.LoginModel;
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Log In</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_login">
            </div>
            <!-- N: the strong typing for LoginModel-->
            <form id="UserLoginForm" asp-controller="UserAuth" asp-action="Login">
                <span class="badge bg-primary text-dark bg-opacity-50">
                    Use: admin@user.com Password: Admin1!<br />
                    or user@example.com Password: User1!
                </span>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="LoginInValid" />
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input class="form-control" asp-for="Email" placeholder="Enter your email address" />
                        <span asp-validation-for="Email" class="text-danger" /> <!-- denotes form-field related exception messages -->
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input class="form-control" asp-for="Password" placeholder="Enter your password" />
                        <span asp-validation-for="Password" class="text-danger" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-8 col-form-label">
                        <div class="form-check">
                            <input class="form-check-input" asp-for="RememberMe" />
                            <label class="form-check-label" asp-for="RememberMe"></label>
                        </div>
                    </div>
                </div>
            </form>         
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" id="login" name="login" class="btn btn-primary">Login</button> <!-- UserLogin.js is wired to this button-->
        </div>
    </div>
</div>

TechTreeWebApp/Views/Shared/_UserRegistrationPartial.cshtml
@model TechTreeWebApp.Models.RegistrationModel;
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Register Account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <div id="alert_placeholder_registration">
            </div><!-- Can be M: by Jquery dynamically i.e BootstrapAlert.js-->
            <form id="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="RegistrationInValid"/>
                <input asp-for="CategoryId" type="hidden" />
                    <div class="form-group row mb-1">
                        <label asp-for="UserName" class="col-form-label col-md-4"></label>
                            <div class="col-md-8">
                                <input asp-for="UserName" id="username" class="form-control" placeholder="Enter your Username" />
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="Email" class="col-form-label col-md-4"></label>
                            <div class="col-md-8">
                                <input class="form-control" asp-for="Email" placeholder="Enter your email " />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>                                    
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="Password" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" class="form-control" placeholder="(Must include atleast 1 uppercase & lowercase, 1 alphanumeric & numeric)" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="ConfirmPassword" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="ConfirmPassword" class="form-control" placeholder="Re-type your password" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="FirstName" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="FirstName" class="form-control" placeholder="Enter your first name" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="LastName" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="LastName" class="form-control" placeholder="Enter your last name" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="Address1" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="Address1" class="form-control" placeholder="(House No./Suite No./Floor/etc)" />
                            <span asp-validation-for="Address1" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="Address2" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                        <input asp-for="Address2" class="form-control" placeholder="(Subdivision, Street, City Name)" />
                            <span asp-validation-for="Address2" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="PostCode" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="PostCode" class="form-control" placeholder="Post Code" />
                            <span asp-validation-for="PostCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row mb-1">
                        <label asp-for="PhoneNumber" class="col-form-label col-md-4"></label>
                        <div class="col-md-8">
                            <input asp-for="PhoneNumber" class="form-control" placeholder="#" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <div class="form-check">                                
                                <input type="checkbox" id="checkbox" asp-for="AcceptTermsAndAgreement"/>
                                <label class="form-check-label" asp-for="AcceptTermsAndAgreement"> I accept the <a href="#">Terms and Condition</a> and <a href="#"> Privacy Policy </a> </label>
                            </div>
                        </div>
                    </div>                      
            </form>            
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" id="register" name="register" class="btn btn-primary">Register Account</button>
            </div>
        </div>
    </div>