TechTreeWebApp/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TechTreeWebApp.Data;
using TechTreeWebApp.Extentions;
using TechTreeWebApp.Models;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly ICategoryItemDetailsGetterService _categoryItemDetailsGetterService;

        public HomeController(ICategoryItemDetailsGetterService categoryItemDetailsGetterService)
        {
            _categoryItemDetailsGetterService = categoryItemDetailsGetterService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = await _categoryItemDetailsGetterService.GetAllCategoryItemDetails();
            IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = categoryItemDetailsModels.GetGroupedCategoryItemsByCategoryModels();

            CategoryDetailsModel categoryDetailsModel = new()
            {
                GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels
            };
            return View(categoryDetailsModel);
        }
    }
}

TechTreeWebApp/Controllers/CategoriesToUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechTreeWebApp.Data;
using TechTreeWebApp.Entities;
using TechTreeWebApp.Models;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Controllers
{
    [Authorize]
    public class CategoriesToUserController : Controller
    {
        private readonly ICategoriesToUserGetterServices _categoriesGetterServices;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDataFunctions _dataFunctions;

        public CategoriesToUserController(UserManager<ApplicationUser> userManager, ICategoriesToUserGetterServices categoriesServices, IDataFunctions dataFunctions)
        {
            _userManager = userManager;
            _categoriesGetterServices = categoriesServices;
            _dataFunctions = dataFunctions;
        }
        public async Task<IActionResult> Index() 
        {
            CategoriesToUserModel categoriesToUserModel = new();
            string userId = _userManager.GetUserAsync(User).Result?.Id;
            if (userId != null) 
            {
                categoriesToUserModel.SelectedCategories = await _categoriesGetterServices.GetCategoriesCurrentlySavedForUser(userId);     
                categoriesToUserModel.Categories = await _categoriesGetterServices.GetCategoriesThatHaveContent();
                categoriesToUserModel.UserId = userId;
            }

            return View(categoriesToUserModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(string[] categoriesSelected) 
        {
            string userId = _userManager.GetUserAsync(User).Result?.Id;
            CategoriesToUserModel categoriesToUserModel = new();

            List<UserCategory> categoriesForUserToAdd = _categoriesGetterServices.GetCategoriesToAddForUser(categoriesSelected, userId);
            List<UserCategory> categoriesForUserToDelete = _categoriesGetterServices.GetCategoriesToDeleteForUser(userId);

            await _dataFunctions.UpdataUserCategoryEntityAsync(categoriesForUserToAdd, categoriesForUserToDelete);
            return RedirectToAction("Index", "Home");
        }
    }
}

TechTreeWebApp/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechTreeWebApp.Data;
using TechTreeWebApp.Entities;
using System.Diagnostics;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Controllers
{
    /// <summary>
    /// When the user clicks on a CategoryTitle, the user is directed to a razor view of the relevant items
    /// </summary>
    public class ContentController : Controller
    {
        private readonly IContentGetterService _contentService;
        public ContentController(IContentGetterService contentService)
        {
            _contentService = contentService;
        }
        public async Task<IActionResult> Index(int categoryItemId)
        {
            Content content = await _contentService.GetContentByCategoryItemID(categoryItemId);
            return View(content); 
        }
    }
}

TechTreeWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TechTreeWebApp.Data;
using TechTreeWebApp.Extentions;
using TechTreeWebApp.Filters;
using TechTreeWebApp.Models;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryItemDetailsGetterService _categoryItemDetailsGetterService;
        private readonly ICategoriesToUserGetterServices _categoriesGetterServices;
        private readonly IEmailService _emailService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public HomeController(ILogger<HomeController> logger, ICategoryItemDetailsGetterService categoryItemDetailsGetterService, ICategoriesToUserGetterServices categoriesGetterServices,   SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IEmailService emailService)
        { // passing via Dependency Injection
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _categoryItemDetailsGetterService = categoryItemDetailsGetterService;
            _categoriesGetterServices = categoriesGetterServices;
            _emailService = emailService;
        }
        [TypeFilter(typeof(AdminAreaAuthorizationFilter))]
        public async Task<IActionResult> Index()
        {
            CategoryDetailsModel categoryDetailsModel = new();
            if (_signInManager.IsSignedIn(User))
            {
                var userId = _userManager.GetUserId(User);
                if (userId != null)
                {
                    IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = await _categoryItemDetailsGetterService.GetCategoryItemDetailsForUser(userId);
                    IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = categoryItemDetailsModels.GetGroupedCategoryItemsByCategoryModels();

                    categoryDetailsModel.GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels;
                    return View(categoryDetailsModel);
                }                
            }
            else
            {
                categoryDetailsModel.Categories = await _categoriesGetterServices.GetCategoriesThatHaveContent();
            }
            
            return View(categoryDetailsModel);
        }
        [Route("[controller]/[action]")]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SendEmail(string recipientEmail, string name, string body)
        {
            bool success = await _emailService.SendEmail(recipientEmail, name, body);
            return success ? StatusCode(200) : StatusCode(500);
        }
        public IActionResult Privacy() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TechTreeWebApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@using TechTreeWebApp.Data
@inject SignInManager<ApplicationUser> signInManager;
@model CategoryDetailsModel;

@{
    ViewData["Title"] = "Home Page";
    const int descriptionLength = 130;
}
@if (signInManager.IsSignedIn(User))
{
    <div class="text-center">
        <h1 class="display-4">Welcome to TechTree!</h1>
    </div>
    <div class="row mt-5">
        <div class="col-md-6">
            <h2>Your Courses</h2>
            <a asp-controller="CategoriesToUser" asp-action="Index" class="btn btn-outline-dark"> Choose your Courses</a> 
        </div>
    </div>      <!-- Your Courses Section-->
    @if (Model.GroupedCategoryItemsByCategoryModels.Count() > 0) 
    {

        <div class="row mt-3">
            <div class="col-md-12">

                @foreach (var cat in Model.GroupedCategoryItemsByCategoryModels)
                {
                    <div class="card mt-2">
                        <!-- User CategoryId for identifying each category -- Bootstrap card for layouting -->
                        <!-- data-toggle & target enncapsulated withing the div to implement a collapse effect -->
                        <h4 class="card-header text-secondary bg-white" style="cursor:pointer" data-bs-toggle="collapse" data-bs-target="#collapse_@cat.Id" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            @cat.Title
                        </h4>
                        <div id="collapse_@cat.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            <hr />
                            @foreach (var item in cat.Items) // .Items refers to an IGrouping<> interface
                            {
                                <div class="mt-2">
                                    <img src="@item.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                                    <h5 class="card-title mt-2">
                                        <!-- En-route to ContentController public async Task<IActionResult> Index(int categoryItemId) -->
                                        <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-categoryItemId="@item.CategoryItemId">@item.CategoryItemTitle</a>
                                    </h5>                                    
                                    @if (item.CategoryItemDescription.Length > descriptionLength)
                                    {
                                        <p class="card-text text-dark mt-2">
                                            @item.CategoryItemDescription.Substring(0, descriptionLength)...
                                        </p>
                                    }
                                    else
                                    {
                                        <p class="card-text text-dark mt-2">
                                        @item.CategoryItemDescription          
                                        </p>
                                    }                                    
                                </div>
                            }
                        </div>
                    </div>
                }

            </div>
        </div>
    }
    else
    {
        <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>
    }
} 
else
{
    <partial name="_DefaultHomePageContentPartial" model="@Model.Categories"></partial>
}



<div class="modal fade" id="UserLoginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <!-- our Home.Index.cshtml then became strongly-typed for CategoryDetailsModel; _UserLoginPartial and _UserRegistrationPartial NOW requires a model -->
    <partial name="_UserLoginPartial" model="new LoginModel
    {
        Email = string.Empty,
        Password = string.Empty,
        RememberMe = false
    }        
    "></partial> <!-- we can update the contents of this div element using jquery code-->
</div>
<div class="modal fade" id="UserRegistrationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserRegistrationPartial" model="new RegistrationModel
        {
            Email = String.Empty,
            Password = String.Empty,
            ConfirmPassword = String.Empty,
            FirstName = String.Empty,
            LastName = String.Empty,
            PhoneNumber = String.Empty,
            Address1 = String.Empty,
            Address2 = String.Empty,
            PostCode = String.Empty,
            AcceptTermsAndAgreement = false
        }" />
</div>

@section Scripts{
    <script src="~/js/email-service.js"></script>
    @{
        await Html.RenderPartialAsync("_AutoScriptsPartial"); <!-- using statements for js included here -->
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}