TechTreeWebApp/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechTreeWebApp.Data;
using TechTreeWebApp.Entities;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoriesAdderService _categoriesAdderService;
        private readonly ICategoriesGetterService _categoriesGetterService;
        private readonly ICategoriesDeleterService _categoriesDeleterService;
        private readonly ICategoriesUpdaterService _categoriesUpdaterService;

        public CategoryController(ApplicationDbContext context, ICategoriesAdderService categoriesAdderService, ICategoriesGetterService categoriesGetterService, ICategoriesDeleterService categoriesDeleterService, ICategoriesUpdaterService categoriesUpdaterService)
        {
            _categoriesAdderService = categoriesAdderService;
            _categoriesGetterService = categoriesGetterService;
            _categoriesDeleterService = categoriesDeleterService;
            _categoriesUpdaterService = categoriesUpdaterService;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
              return View(await _categoriesGetterService.GetAllCategories());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoriesGetterService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                await _categoriesAdderService.AddCategory(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoriesGetterService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _categoriesUpdaterService.UpdateCategory(category);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoriesGetterService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _categoriesGetterService.GetCategoryById(id);

            if (category != null)
            {
                await _categoriesDeleterService.DeleteCategory(category);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TechTreeWebApp/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TechTreeWebApp.Data;
using TechTreeWebApp.Extentions;
using TechTreeWebApp.Models;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly ICategoryItemDetailsGetterService _categoryItemDetailsGetterService;

        public HomeController(ICategoryItemDetailsGetterService categoryItemDetailsGetterService)
        {
            _categoryItemDetailsGetterService = categoryItemDetailsGetterService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = await _categoryItemDetailsGetterService.GetAllCategoryItemDetails();
            IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = categoryItemDetailsModels.GetGroupedCategoryItemsByCategoryModels();

            CategoryDetailsModel categoryDetailsModel = new()
            {
                GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels
            };
            return View(categoryDetailsModel);
        }
    }
}

TechTreeWebApp/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TechTreeWebApp.Data;
using TechTreeWebApp.Entities;
using System.Diagnostics;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Controllers
{
    /// <summary>
    /// When the user clicks on a CategoryTitle, the user is directed to a razor view of the relevant items
    /// </summary>
    public class ContentController : Controller
    {
        private readonly IContentGetterService _contentService;
        public ContentController(IContentGetterService contentService)
        {
            _contentService = contentService;
        }
        public async Task<IActionResult> Index(int categoryItemId)
        {
            Content content = await _contentService.GetContentByCategoryItemID(categoryItemId);
            return View(content); 
        }
    }
}

TechTreeWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TechTreeWebApp.Data;
using TechTreeWebApp.Extentions;
using TechTreeWebApp.Filters;
using TechTreeWebApp.Models;
using TechTreeWebApp.ServiceContracts;

namespace TechTreeWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryItemDetailsGetterService _categoryItemDetailsGetterService;
        private readonly ICategoriesToUserGetterServices _categoriesGetterServices;
        private readonly IEmailService _emailService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public HomeController(ILogger<HomeController> logger, ICategoryItemDetailsGetterService categoryItemDetailsGetterService, ICategoriesToUserGetterServices categoriesGetterServices,   SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IEmailService emailService)
        { // passing via Dependency Injection
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _categoryItemDetailsGetterService = categoryItemDetailsGetterService;
            _categoriesGetterServices = categoriesGetterServices;
            _emailService = emailService;
        }
        [TypeFilter(typeof(AdminAreaAuthorizationFilter))]
        public async Task<IActionResult> Index()
        {
            CategoryDetailsModel categoryDetailsModel = new();
            if (_signInManager.IsSignedIn(User))
            {
                var userId = _userManager.GetUserId(User);
                if (userId != null)
                {
                    IEnumerable<CategoryItemDetailsModel> categoryItemDetailsModels = await _categoryItemDetailsGetterService.GetCategoryItemDetailsForUser(userId);
                    IEnumerable<GroupedCategoryItemsByCategoryModel> groupedCategoryItemsByCategoryModels = categoryItemDetailsModels.GetGroupedCategoryItemsByCategoryModels();

                    categoryDetailsModel.GroupedCategoryItemsByCategoryModels = groupedCategoryItemsByCategoryModels;
                    return View(categoryDetailsModel);
                }                
            }
            else
            {
                categoryDetailsModel.Categories = await _categoriesGetterServices.GetCategoriesThatHaveContent();
            }
            
            return View(categoryDetailsModel);
        }
        [Route("[controller]/[action]")]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SendEmail(string recipientEmail, string name, string body)
        {
            bool success = await _emailService.SendEmail(recipientEmail, name, body);
            return success ? StatusCode(200) : StatusCode(500);
        }
        public IActionResult Privacy() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TechTreeWebApp/Areas/Admin/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@using TechTreeWebApp.Data
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> UserManager;
@model CategoryDetailsModel;

@{
    ViewData["Title"] = "Home Page";
}
@if (signInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <div class="text-center">
        <h1 class="display-4">Welcome to TechTree!</h1>
    </div>
    <div class="row mt-5">
        <div class="col-md-6">
            <h2>All Courses</h2>
            <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="btn btn-outline-dark">Manage Courses</a>
        </div>
    </div>      <!-- Your Courses Section-->
    @if (Model.GroupedCategoryItemsByCategoryModels.Count() > 0)
    {
        <div class="row mt-3">
            <div class="col-md-12">

                @foreach (var cat in Model.GroupedCategoryItemsByCategoryModels)
                {
                    <div class="card mt-2">
                        <!-- User CategoryId for identifying each category -- Bootstrap card for layouting -->
                        <!-- data-toggle & target enncapsulated withing the div to implement a collapse effect -->
                        <h4 class="card-header text-secondary bg-white" style="cursor:pointer" data-bs-toggle="collapse" data-bs-target="#collapse_@cat.Id" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            @cat.Title
                        </h4>
                        <div id="collapse_@cat.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@cat.Id">
                            <hr />
                            @foreach (var item in cat.Items) // .Items refers to an IGrouping<> interface
                            {
                                <div class="mt-2">
                                    <img src="@item.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                                    <h5 class="card-title mt-2">
                                        <!-- En-route to ContentController public async Task<IActionResult> Index(int categoryItemId) -->
                                        <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-categoryItemId="@item.CategoryItemId">@item.CategoryItemTitle</a>
                                    </h5>
                                    <p class="card-text text-dark mt-2">
                                        @item.CategoryItemDescription
                                    </p>
                                </div>
                            }
                        </div>
                    </div>
                }

            </div>
        </div>
    }
    else
    {
        <h4 class="mt-2 text-warning">There are currently no courses saved in the system.</h4>
    }
} 